kubectl kustomize infra-deployments/wrenai/kustomizations --enable-helm > infra-deployments/wrenai/kustomizations/wrenai.kustimized.yaml
kubectl apply -f deployment/kustomizations/examples/secret-wren_example.yaml -n wren

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai-system
### Overwride with causion
images:
  - name: ghcr.io/canner/wren-bootstrap
    newTag: 0.1.5 # WREN_BOOTSTRAP_VERSION
  - name: ghcr.io/canner/wren-engine
    newTag: 0.9.0 # WREN_ENGINE_VERSION
  - name: ghcr.io/canner/wren-ui
    newTag: 0.9.2 # WREN_UI_VERSION
  - name: ghcr.io/canner/wren-ai-service
    newTag: commit-391ea49 # WREN_AI_SERVICE_VERSION
  - name: ghcr.io/canner/wren-engine-ibis
    newTag: 0.9.0 # IBIS_SERVER_VERSION

resources:
- "https://github.com/Canner/WrenAI.git/deployment/kustomizations?ref=0.15.4-rc"
#- "https://github.com/Canner/WrenAI.git/deployment/kustomizations?ref=0.5.1"

### Best practice is to create and deploy Secrets manually, not as part of kustomization or GitOps!
- examples/secret-wren_example.yaml
- examples/ingress-wren.yaml
- examples/certificate-wren.yaml


### Additional customizations here
patches:
### for DualStack IP k8s cluster
- path: patches/service.yaml
  target:
    kind: Service
    name: wren-ai-service

### removes the Ingress from the original repo
- path: patches/rm-ingress.yaml
  target:
    kind: Ingress
    name: wren-ui-ingress

### removes the Certificate from the original repo
- path: patches/rm-certificate.yaml
  target:
    kind: Certificate
    name: wren-ui.myhost.net

### Patches values from the original repo in ConfigMap 
- path: patches/rm-cm.yaml
  target:
    kind: ConfigMap
    name: wren-ai-service-config

- path: patches/cm.yaml
  target:
    kind: ConfigMap
    name: wren-config
