apiVersion: v1
kind: Secret
metadata:
  name: repo-docker-io
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
  annotations:
    managed-by: argocd.argoproj.io
stringData:
  url: registry-1.docker.io
  name: docker-io
  type: helm
  project: default
  enableOCI: "true"
