apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
spec:
  destination:
    namespace: cert-manager
    server: 'https://kubernetes.default.svc'

  sources:
  - repoURL: 'https://charts.jetstack.io'
    targetRevision: v1.14.3
    chart: cert-manager
    helm:
        valueFiles:
          - $values/infra-deployments/cert-manager/helm-values.yaml
    
  - repoURL: 'git@github.com:qdrddr/WrenAi-k8s.git'
    targetRevision: main
    ref: values

  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
