installCRDs: true

tolerations:
  - key: "infra"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
    operator: Exists